# Generated by Django 4.1.2 on 2024-04-13 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import src.validators.index
import re
from configs.helpers.menu import resources as menu_resources, resources_admin
from configs.helpers.menu_resources import menuResources
from django.contrib.auth.models import Group
from configs.seeds.AuthSeed import DocumentTypeSeed,GendersSeed, GroupsSeed, PersonsSeed, UsersSeed
from configs.seeds.PaisesSeed import CiudadesSeed, DepartamentosSeed, PaisesSeed
from django.contrib.auth.hashers import make_password


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]
    
    def insert_init_data(apps, schema_editor):
        
        Paises = apps.get_model("auth_module", "Pais") # type: ignore
        Departamentos = apps.get_model("auth_module", "Departamento") # type: ignore
        Ciudades = apps.get_model("auth_module", "Ciudad") # type: ignore
        
        Paises.objects.bulk_create([Paises(**data) for data in PaisesSeed])
        Departamentos.objects.bulk_create([Departamentos(**data) for data in DepartamentosSeed])
        Ciudades.objects.bulk_create([Ciudades(**data) for data in CiudadesSeed])
        
        User = apps.get_model("auth_module", "User") # type: ignore
        Person = apps.get_model("auth_module", "Persons") # type: ignore
        User_roles = apps.get_model("auth_module", "user_groups") # type: ignore
        User_documents = apps.get_model("auth_module", "document_types") # type: ignore
        User_genders = apps.get_model("auth_module", "genders") # type: ignore
       
        Group.objects.bulk_create([Group(**data) for data in GroupsSeed])
        User_documents.objects.bulk_create([User_documents(**data) for data in DocumentTypeSeed])
        User_genders.objects.bulk_create([User_genders(**data) for data in GendersSeed])
        Person.objects.bulk_create([Person(**data) for data in PersonsSeed])
        User.objects.bulk_create([User(**data) for data in UsersSeed])
        
        # CARGA DE ROLES DE USUARIOS ESPECIFICOS
        User_roles.objects.create(user_id=1, group_id=1)
        User_roles.objects.create(user_id=2, group_id=1)
        User_roles.objects.create(user_id=3, group_id=2)
        User_roles.objects.create(user_id=4, group_id=2)

        # CARGA DE RECURSOS
        Resources = apps.get_model("auth_module", "Resources")  # type: ignore
        resources = []
        menuResources(menu_resources, resources, Resources, 1)

        resources = Resources.objects.bulk_create(resources)

        Resources_roles = apps.get_model("auth_module", "Resources_roles")  # type: ignore
        list_resources_roles = []
        roles = Group.objects.all()
        
        for rol in roles:
            if rol.name == "Funcionario":
                for r in resources_admin:
                    resource_instance = Resources.objects.get(id=r["id"])
                    list_resources_roles.append(Resources_roles(rolesId_id=rol.id, resourcesId=resource_instance))  # type: ignore
            if rol.name == "Admin":
                for r in resources:
                    list_resources_roles.append(
                        Resources_roles(rolesId_id=rol.id, resourcesId=r) # type: ignore
                    )

        Resources_roles.objects.bulk_create(list_resources_roles)

    def undo_insert_data(apps, schema_editor):
        Group.objects.all().delete()
        Paises = apps.get_model("auth_module", "Pais") # type: ignore
        Departamentos = apps.get_model("auth_module", "Departamento") # type: ignore
        Ciudades = apps.get_model("auth_module", "Ciudad") # type: ignore
        Person = apps.get_model("auth_module", "Persons") # type: ignore
        User = apps.get_model("auth_module", "User") # type: ignore
        User_roles = apps.get_model("auth_module", "user_groups") # type: ignore
        User_documents = apps.get_model("auth_module", "document_types") # type: ignore
        User_genders = apps.get_model("auth_module", "genders") # type: ignore
        Resources = apps.get_model("auth_module", "Resources")  # type: ignore
        Resources_roles = apps.get_model("auth_module", "Resources_roles")  # type: ignore
        
        Paises.objects.all().delete()
        Departamentos.objects.all().delete()
        Ciudades.objects.all().delete()
        Person.objects.all().delete()
        User.objects.all().delete()
        User_roles.objects.all().delete()
        User_documents.objects.all().delete()
        User_genders.objects.all().delete()
        Resources.objects.all().delete()
        Resources_roles.objects.all().delete()


    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('updateAt', models.DateField(auto_now=True, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=256, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('resetToken', models.CharField(blank=True, max_length=256, null=True)),
                ('avatar', models.CharField(blank=True, max_length=256, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Users',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('updateAt', models.DateField(auto_now=True, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('sap', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('updateAt', models.DateField(auto_now=True, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Document_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('updateAt', models.DateField(auto_now=True, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('userCreate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('userUpdate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document_types',
                'verbose_name_plural': 'Document_types',
            },
        ),
        migrations.CreateModel(
            name='Genders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('updateAt', models.DateField(auto_now=True, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('userCreate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('userUpdate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Genders',
                'verbose_name_plural': 'Genders',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('updateAt', models.DateField(auto_now=True, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('sap', models.CharField(max_length=10)),
                ('userCreate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('userUpdate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('updateAt', models.DateField(auto_now=True, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('path', models.CharField(max_length=256)),
                ('id_padre', models.IntegerField()),
                ('method', models.CharField(max_length=256)),
                ('icono', models.CharField(max_length=256)),
                ('link', models.CharField(max_length=256)),
                ('titulo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Resources',
                'verbose_name_plural': 'Resources',
            },
        ),
        migrations.CreateModel(
            name='Resources_roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('updateAt', models.DateField(auto_now=True, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('resourcesId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='auth_module.resources')),
                ('rolesId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resouces_roles', to='auth.group')),
                ('userCreate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('userUpdate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resources_roles',
                'verbose_name_plural': 'Resources_roles',
            },
        ),
        migrations.AddField(
            model_name='resources',
            name='roles',
            field=models.ManyToManyField(db_index=True, related_name='resources_roles', through='auth_module.Resources_roles', to='auth.group'),
        ),
        migrations.AddField(
            model_name='resources',
            name='userCreate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resources',
            name='userUpdate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('updateAt', models.DateField(auto_now=True, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('fullname', models.CharField(default='', max_length=150)),
                ('identification', models.CharField(default='', max_length=40, unique=True)),
                ('address', models.CharField(blank=True, default='', max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(default='', max_length=50)),
                ('phone2', models.CharField(blank=True, default='', max_length=50)),
                ('fecha_expedicion', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(default='', max_length=254, verbose_name='email address')),
                ('email2', models.EmailField(blank=True, default='', max_length=254, verbose_name='email address')),
                ('graduado', models.BooleanField(blank=True, default=True)),
                ('funcionario', models.BooleanField(blank=True, default=False)),
                ('status', models.BooleanField(default=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_module.departamento')),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_module.document_types')),
                ('gender_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gender_types', to='auth_module.genders')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_module.ciudad')),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_module.pais')),
                ('userCreate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('userUpdate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Persons',
                'verbose_name_plural': 'Persons',
                'unique_together': {('fullname', 'identification')},
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_module.pais'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='userCreate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departamento',
            name='userUpdate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_module.departamento'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_module.pais'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='userCreate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='userUpdate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_module.persons'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(db_index=True, related_name='user_roles', to='auth.group'),
        ),
        migrations.AddField(
            model_name='user',
            name='userCreate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='userUpdate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.RunPython(
            insert_init_data, reverse_code=undo_insert_data, atomic=True
        ),
    ]
